server:
  port: 2222   # HTTP port
  
logging:
  file: logs/eurka.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.example.demo: 'DEBUG'

# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false 
  server:
    enableSelfPreservation: false

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf 

